logo_clinica: <%= clinic %>
tipo: <%= type_complete %>
paciente: <%= pacient.capitalize %>
ficha: 
tutor: 
medico: 
especie: <%= specie %>
edad: <%= age %>
sexo: <%= sex %>
estudio: <%= study_complete %>
date: <%= beauty_day %>
antecedentes: 
<%= study_partial %>